const Map<String, String> en_US = {
  'app_name': 'Xlist',
  'pull_down_new_file': 'New File',
  'pull_down_new_folder': 'New Folder',
  'pull_down_upload_file': 'Upload File',
  'pull_down_upload_image': 'Upload Image',
  'pull_down_upload_video': 'Upload Video',
  'pull_down_refresh': 'Refresh',
  'pull_down_force_refresh': 'Force Refresh',
  'pull_down_list': 'List',
  'pull_down_grid': 'Grid',
  'pull_down_time': 'Time',
  'pull_down_name': 'Name',
  'pull_down_copy_link': 'Copy Link',
  'pull_down_download_file': 'Add to Download List',
  'pull_down_save_image': 'Save to Album',

  // General
  'search': 'Search',
  'download': 'Download',
  'file_size': 'File Size',
  'directory': 'Directory',
  'mount_type': 'Mount Type',
  'modify_time': 'Modify Time',
  'file_type': 'File Type',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'close': 'Close',
  'paused': 'Paused',
  'resume': 'Resume',
  'delete': 'Delete',
  'switch': 'Switch',
  'setting': 'Settings',
  'general': 'General',
  'server': 'Server',
  'download_manager': 'Download',
  'preview': 'Preview',
  'document': 'Document',
  'image': 'Image',
  'video': 'Video',
  'audio': 'Audio',
  'feedback': 'Feedback',
  'about': 'About',
  'version': 'Version',
  'failed': 'Failed',
  'test': 'Test',
  'save': 'Save',
  'rename': 'Rename',
  'move': 'Move',
  'copy': 'Copy',
  'more': 'More',
  'favorite': 'Favorite',
  'recent': 'Recent',
  'premium': 'Premium',
  'play_speed': 'Play Speed',

  // Toasts
  'toast_no_storage_permission': 'No Storage Permission',
  'toast_get_object_fail': 'Get file address failed',
  'toast_download_exist': 'File already exists',
  'toast_get_download_url_fail': 'Get download url failed',
  'toast_save_image_fail': 'Save image failed',
  'toast_save_success': 'Save success',
  'toast_download_add_success': 'Added to download list',
  'toast_download_fail': 'Download failed',
  'toast_rename_success': 'Rename success',
  'toast_copy_success': 'Copy success',
  'toast_move_success': 'Move success',
  'toast_remove_success': 'Remove success',
  'toast_remove_success_all': 'Remove all success',
  'toast_mkdir_success': 'Mkdir success',
  'toast_newfile_success': 'New file success',
  'toast_switch_success': 'Switch success',
  'toast_upload_success': 'Upload success',
  'toast_upload_loading': 'Uploading...',
  'toast_download_unfinished': 'Download unfinished',
  'toast_get_user_info_fail': 'Get user info failed',
  'toast_current_play_file': 'Current play file',
  'toast_current_audio_track': 'Current audio track, no need to switch',
  'toast_subtitle_closed': 'Subtitle closed',
  'toast_current_subtitle': 'Current subtitle, no need to switch',
  'toast_switch_loading': 'Switching...',
  'toast_switch_subtitle_fail': 'Switch subtitle failed',
  'toast_favorite_success': 'Added to Favorite',

  // Dialogs
  'dialog_prompt_title': 'Prompt',
  'dialog_rename_title': 'Rename',
  'dialog_rename_message': 'Please enter a new name',
  'dialog_rename_hint': 'File name',
  'dialog_remove_message': 'Are you sure you want to delete it?',
  'dialog_remove_message_all': 'Are you sure you want to clear it?',
  'dialog_switch_message': 'Are you sure you want to switch servers?',
  'dialog_mkdir_title': 'New Folder',
  'dialog_mkdir_message': 'Please enter the folder name',
  'dialog_mkdir_hint': 'Folder name',
  'dialog_newfile_title': 'New File',
  'dialog_newfile_message': 'Please enter the file name',
  'dialog_newfile_hint': 'File name',

  // Components
  'add_server_title': 'New Server',
  'add_server_toast_pass': 'Test passed',
  'add_server_toast_anonymous_fail': 'Anonymous access is disabled',
  'add_server_toast_url_empty': 'Please enter the server address',
  'add_server_toast_url_invalid':
      'Server address must start with http:// or https://',
  'add_server_toast_url_user_invalid':
      'Server address and username are invalid',
  'add_server_toast_save_success': 'Save success',
  'add_server_dialog_2fa_title': '2FA Verification',
  'add_server_dialog_2fa_hint': 'Please enter your OTP verification code',
  'add_server_toast_2fa_error': '2FA verification failed',
  'add_server_section_header': 'Please enter server information',
  'add_server_section_footer':
      'The server address format is: https://example.com.\nPlease test whether the server address and username are correct before saving.',
  'add_server_textfield_url': 'Server Address',
  'add_server_textfield_url_hint':
      'Please enter the server address (https://example.com)',
  'add_server_textfield_username': 'Username',
  'add_server_textfield_username_hint': 'Please enter the username',
  'add_server_textfield_password': 'Password',
  'add_server_textfield_password_hint': 'Please enter the password',

  // Pages
  'homepage_title': 'File Manager',
  'homepage_empty_server_title': 'Please create a Alist server',
  'homepage_empty_server_help': 'Learn about Alist?',
  'homepage_empty_server_button': 'New Server',
  'directory_root_title': 'Select target folder',
  'directory_empty_description': 'No more directories!!!',
  'file_unsupported_description':
      'This type of file is not supported for opening, please add it to the download list\nAfter the download is complete, you can use other applications to open and preview',
  'video_switch_subtitle': 'Switch Subtitle',
  'video_switch_audio': 'Switch Audio',
  'video_tab_introduction': 'Introduction',
  'video_tab_playlist': 'Playlist',
  'detail_dialog_password_title': 'Password',
  'detail_dialog_password_message': 'Please enter the password',
  'detail_dialog_password_hint': 'Password',

  'setting_theme': 'Theme',
  'setting_autoplay': 'Autoplay',
  'setting_hardware': 'Hardware',
  'setting_preview_image': 'Preview',
  'setting_background_playback': 'Background',
  'setting_review': 'Review Xlist',
  'setting_review_description': 'Five star',
  'setting_other_app_open': 'Open with other apps',
  'setting_download_empty': 'No download file',
  'setting_download_used': 'Used space',
  'setting_download_manager_file': 'Swipe left to manage files',
  'setting_preview_audio_title': 'Set the audio type to preview',
  'setting_preview_document_title': 'Set the document type to preview',
  'setting_preview_image_title': 'Set the image type to preview',
  'setting_preview_video_title': 'Set the video type to preview',
  'setting_recent_title': 'Recent',
  'setting_recent_clear': 'Clear',
  'setting_recent_empty': 'No recent',
  'setting_recent_description': 'Swipe left to delete browsing history',
  'setting_favorite_empty': 'No favorite',
  'setting_favorite_description': 'Swipe left to delete favorites',
  'setting_server_new': 'New',
  'setting_server_title': 'Swipe left to switch and delete the server',
  'setting_upgrade': 'Upgrade',
  'setting_upgraded': 'Upgraded',
  'setting_premium_buy': 'Buy',
  'setting_premium_buy_description': 'One-time purchase, permanent use',
  'setting_premium_restore': 'Restore',
  'setting_premium_upgrade': 'Upgrade to Xlist Premium',
  'setting_premium_upgrade_description':
      'With a one-time purchase, you will permanently receive all of the following premium features',
  'setting_premium_upgraded': '🎉 Upgraded to Xlist Premium',
  'setting_premium_upgraded_description':
      'You have permanent access to all of the following premium features',
  'setting_premium_favorite':
      'Bookmark your favorite files or folders, and find what you care about more easily',
  'setting_premium_recent':
      'Record your recently viewed files, quickly find the last previewed file',
  'setting_premium_preview':
      'Displays a preview of the media file, which allows you to visualize the contents of the file',
  'setting_premium_advanced': 'Advanced Features',
  'setting_premium_advanced_description':
      'Take your experience to the next level with all the advanced features',
  'setting_premium_forever': 'Permanent update',
  'setting_premium_forever_description':
      'Access to all new features in future updated versions',
  'setting_premium_support': 'Support for Developers',
  'setting_premium_support_description':
      'Help developers to better maintain the software and provide you with a better experience',

  'fijkplayer_subtitle': 'Subtitle',
  'fijkplayer_subtitle_close': 'Close subtitles',
  'fijkplayer_audio_track': 'Audio',
  'fijkplayer_next': 'Next',
  'fijkplayer_buffering': 'Buffering...',
  'fijkplayer_retry': 'Click to retry',

  // Error
  'no_data': 'No data',
};
