const Map<String, String> zh_Hans = {
  'app_name': 'Xlist',
  'pull_down_new_file': '新建文件',
  'pull_down_new_folder': '新建文件夹',
  'pull_down_upload_file': '上传文件',
  'pull_down_upload_image': '上传图片',
  'pull_down_upload_video': '上传视频',
  'pull_down_refresh': '刷新',
  'pull_down_force_refresh': '强制刷新',
  'pull_down_list': '列表',
  'pull_down_grid': '网格',
  'pull_down_time': '时间',
  'pull_down_name': '名称',
  'pull_down_copy_link': '复制链接',
  'pull_down_download_file': '添加到下载列表',
  'pull_down_save_image': '保存到相册',

  // General
  'search': '搜索',
  'download': '下载',
  'file_size': '文件大小',
  'directory': '目录',
  'mount_type': '挂载类型',
  'modify_time': '修改时间',
  'file_type': '文件类型',
  'confirm': '确定',
  'cancel': '取消',
  'close': '关闭',
  'paused': '暂停',
  'resume': '恢复',
  'delete': '删除',
  'switch': '切换',
  'setting': '设置',
  'general': '通用',
  'server': '服务器',
  'download_manager': '下载管理',
  'preview': '预览',
  'document': '文档',
  'image': '图片',
  'video': '视频',
  'audio': '音频',
  'feedback': '问题反馈',
  'about': '关于',
  'version': '版本',
  'failed': '失败',
  'test': '测试',
  'save': '保存',
  'rename': '重命名',
  'move': '移动',
  'copy': '复制',
  'more': '更多',
  'favorite': '收藏',
  'recent': '最近浏览',
  'premium': '高级版',
  'play_speed': '播放速度',

  // Toasts
  'toast_no_storage_permission': '没有存储权限',
  'toast_get_object_fail': '获取文件地址失败',
  'toast_download_exist': '已经在下载列表中',
  'toast_get_download_url_fail': '获取下载地址失败',
  'toast_save_image_fail': '保存图片失败',
  'toast_save_success': '保存成功',
  'toast_download_add_success': '已添加到下载列表',
  'toast_download_fail': '文件下载失败',
  'toast_rename_success': '重命名成功',
  'toast_copy_success': '复制成功',
  'toast_move_success': '移动成功',
  'toast_remove_success': '删除成功',
  'toast_remove_success_all': '清空成功',
  'toast_mkdir_success': '新建成功',
  'toast_newfile_success': '新建成功',
  'toast_switch_success': '切换成功',
  'toast_upload_success': '上传成功',
  'toast_upload_loading': '上传中...',
  'toast_download_unfinished': '下载未完成',
  'toast_get_user_info_fail': '获取用户信息失败',
  'toast_current_play_file': '当前播放文件',
  'toast_current_audio_track': '当前音轨, 无需切换',
  'toast_subtitle_closed': '字幕已关闭',
  'toast_current_subtitle': '当前字幕, 无需切换',
  'toast_switch_loading': '切换中...',
  'toast_switch_subtitle_fail': '切换字幕失败',
  'toast_favorite_success': '已加入收藏',

  // Dialogs
  'dialog_prompt_title': '提示',
  'dialog_rename_title': '重命名',
  'dialog_rename_message': '请输入新的名称',
  'dialog_rename_hint': '文件名',
  'dialog_remove_message': '确定要删除吗？',
  'dialog_remove_message_all': '确定要清空吗？',
  'dialog_switch_message': '确定要切换服务器吗？',
  'dialog_mkdir_title': '新建文件夹',
  'dialog_mkdir_message': '请输入文件夹名称',
  'dialog_mkdir_hint': '文件夹名称',
  'dialog_newfile_title': '新建文件',
  'dialog_newfile_message': '请输入文件名称',
  'dialog_newfile_hint': '文件名称',

  // Components
  'add_server_title': '新建服务器',
  'add_server_toast_pass': '测试通过',
  'add_server_toast_anonymous_fail': '服务器禁止匿名访问',
  'add_server_toast_url_empty': '请填写服务器地址',
  'add_server_toast_url_invalid': '服务器地址必须 http:// 或者 https:// 开头',
  'add_server_toast_url_user_invalid': '服务器地址和用户名无效',
  'add_server_toast_save_success': '保存成功',
  'add_server_dialog_2fa_title': '2FA 验证',
  'add_server_dialog_2fa_hint': '请输入您的 OTP 验证码',
  'add_server_toast_2fa_error': '2FA 验证失败',
  'add_server_section_header': '请填写服务器信息',
  'add_server_section_footer':
      '服务器地址格式为：https://example.com。\n请先测试服务器地址和用户名是否正确，再保存。',
  'add_server_textfield_url': '服务器地址',
  'add_server_textfield_url_hint': '请输入服务器地址 (https://example.com)',
  'add_server_textfield_username': '用户名',
  'add_server_textfield_username_hint': '请输入用户名',
  'add_server_textfield_password': '密码',
  'add_server_textfield_password_hint': '请输入密码',

  // Pages
  'homepage_title': '文件管理',
  'homepage_empty_server_title': '请先新建一个 Alist 服务器',
  'homepage_empty_server_help': '了解 Alist ?',
  'homepage_empty_server_button': '新建',
  'directory_root_title': '选择目标文件夹',
  'directory_empty_description': '没有更多目录啦!!!',
  'file_unsupported_description': '暂不支持打开此类文件, 请添加到下载列表\n下载完成后, 可以使用其他应用打开并预览',
  'video_switch_subtitle': '切换字幕',
  'video_switch_audio': '切换音轨',
  'video_tab_introduction': '简介',
  'video_tab_playlist': '播放列表',
  'detail_dialog_password_title': '密码',
  'detail_dialog_password_message': '请输入密码',
  'detail_dialog_password_hint': '密码',

  'setting_theme': '个性化',
  'setting_autoplay': '自动播放',
  'setting_hardware': '硬件解码',
  'setting_preview_image': '预览图',
  'setting_background_playback': '后台播放',
  'setting_review': '评价 Xlist',
  'setting_review_description': '麻烦客官给个好评哦!',
  'setting_other_app_open': '其他应用打开',
  'setting_download_empty': '没有下载文件',
  'setting_download_used': '已用空间',
  'setting_download_manager_file': '左滑管理文件',
  'setting_preview_audio_title': '设置预览的音频类型',
  'setting_preview_document_title': '设置预览的文档类型',
  'setting_preview_image_title': '设置预览的图片类型',
  'setting_preview_video_title': '设置预览的视频类型',
  'setting_recent_title': '最近浏览',
  'setting_recent_clear': '清空',
  'setting_recent_empty': '没有最近浏览数据',
  'setting_recent_description': '左滑可以删除浏览记录',
  'setting_favorite_empty': '没有收藏数据',
  'setting_favorite_description': '左滑可以删除收藏',
  'setting_server_new': '新建',
  'setting_server_title': '左滑可以切换和删除服务器',
  'setting_upgrade': '了解更多',
  'setting_upgraded': '已升级',
  'setting_premium_buy': '立即购买',
  'setting_premium_buy_description': '一次性付费, 永久使用',
  'setting_premium_restore': '恢复购买',
  'setting_premium_upgrade': '升级到 Xlist 高级版',
  'setting_premium_upgrade_description': '一次性购买, 您将永久获得以下所有高级功能',
  'setting_premium_upgraded': '🎉 已升级到 Xlist 高级版',
  'setting_premium_upgraded_description': '您已永久获得以下所有高级功能',
  'setting_premium_favorite': '收藏自己喜欢的文件或者文件夹, 更便捷的找到您关注的内容',
  'setting_premium_recent': '记录您最近浏览过的文件, 快速找到上次预览的文件',
  'setting_premium_preview': '显示媒体文件的预览图, 预览图可以让您更直观的了解文件内容',
  'setting_premium_advanced': '高级功能',
  'setting_premium_advanced_description': '使用所有高级功能, 让您的使用体验更上一层楼',
  'setting_premium_forever': '永久更新',
  'setting_premium_forever_description': '可以获得未来更新版本的所有新功能',
  'setting_premium_support': '支持开发者',
  'setting_premium_support_description': '帮助开发者更好的维护软件, 为您提供更好的体验',

  'fijkplayer_subtitle': '字幕',
  'fijkplayer_subtitle_close': '关闭字幕',
  'fijkplayer_audio_track': '音轨',
  'fijkplayer_next': '下一集',
  'fijkplayer_buffering': '正在缓冲...',
  'fijkplayer_retry': '点击重试',

  // 暂无数据
  'no_data': '暂无数据',
};
